import * as fs from "node:fs";
import * as path from "node:path";
import { z } from "zod";
import { findDshRoot } from "@dsh/repo";

// ---- Schema ----

const verifyResultSchema = z.object({
  command: z.string(),
  status: z.enum(["passed", "failed"]),
  exit_code: z.number(),
  output: z.string(),
  duration_ms: z.number(),
});

const toolCallRecordSchema = z.object({
  name: z.string(),
  arguments: z.record(z.unknown()),
  status: z.enum(["success", "error"]),
  summary: z.string(),
});

const toolRoundRecordSchema = z.object({
  round: z.number(),
  calls: z.array(toolCallRecordSchema),
});

const planContractAttemptSchema = z.object({
  stage: z.enum(["finalize", "protocol_repair"]),
  attempt: z.number(),
  status: z.enum(["valid", "invalid", "provider_error"]),
  failure_reason: z.string().optional(),
  response_excerpt: z.string(),
  response_sha256: z.string(),
  tool_rounds_before_finalize: z.number(),
  protocol_recovered: z.boolean().optional(),
  protocol_recovery_reason: z.string().optional(),
  created_at: z.string(),
});

const patchRecordSchema = z.object({
  round: z.number(),
  phase: z.enum(["patch", "repair"]).optional(),
  patch: z.string(),
  apply_status: z.enum(["ok", "failed", "skipped", "partial_ok"]),
  files_changed: z.array(z.string()),
  tool_rounds: z.array(toolRoundRecordSchema).optional(),
  rolled_back: z.boolean().optional(),
  rollback_reason: z.enum(["regression", "stagnation"]).optional(),
  // Set when patch loop produced ≥1 successful change but plan.files were not
  // fully covered. Carries the structured "missing files" signal forward to
  // repair (see spec docs/specs/2026-05-07-patch-completeness.md §3.4).
  patch_incomplete_reason: z.string().optional(),
  // Patch coverage state machine v2 (spec docs/specs/2026-05-19-patch-pipeline-
  // coverage-state-machine.md §4.8). Populated by runPatchPipeline. All optional
  // so task-state.json files written by earlier versions still parse.
  coverage: z.enum(["full", "partial"]).optional(),
  covered_required_files: z.array(z.string()).optional(),
  missing_required_files: z.array(z.string()).optional(),
  coverage_finalization_attempted: z.boolean().optional(),
  plan_file_contract_version: z.enum(["legacy", "v2"]).optional(),
  patch_partial_reason: z.string().optional(),
  // True when any of this repair round's inner tool/final responses went
  // through DSML envelope salvage. Telemetry for Bug A
  // (ledger §8 patchloop-dsml-content-leak) — explore stage uses the
  // patchRoundSchema's homonymous field; repair uses this one on PatchRecord.
  dsml_salvage_applied: z.boolean().optional(),
  repair_progress: z.enum([
    "advanced_required_coverage",
    "changed_non_required_files",
    "empty_patch",
    "apply_failed",
    "no_required_coverage_progress",
  ]).optional(),
  repair_stall_reason: z.enum([
    "empty_patch",
    "missing_required_files",
    "no_required_coverage_progress",
  ]).optional(),
  repair_semantic_hints: z.array(z.string()).optional(),
  blocked_write_shell_guidance: z.boolean().optional(),
  rename_intent_detected: z.boolean().optional(),
  deterministic_reference_repair: z.boolean().optional(),
});

const patchRoundSchema = z.object({
  round: z.number(),
  action: z.enum(["tools", "change", "done", "invalid"]),
  tool_calls: z.array(toolCallRecordSchema).optional(),
  change: z.object({
    op: z.enum(["CREATE", "PATCH", "SEARCH_REPLACE", "INSERT", "DELETE", "RENAME"]),
    file: z.string(),
    apply_status: z.enum(["ok", "failed"]),
    apply_error: z.string().optional(),
    raw_block: z.string(),
  }).optional(),
  invalid_reason: z.string().optional(),
  reasoning_excerpt: z.string().optional(),
  // When DONE is accepted with uncovered plan.files, carries the uncovered
  // file list for downstream consumers (benchmark reporter, repair diagnostics).
  incomplete_note: z.string().optional(),
  // True when this round's content went through DSML envelope salvage
  // (recovered=true from recoverDsmlWrappedChange). Telemetry for Bug A
  // (ledger §8 patchloop-dsml-content-leak) frequency observation.
  dsml_salvage_applied: z.boolean().optional(),
  duration_ms: z.number(),
});

const planSchema = z.object({
  summary: z.string(),
  files: z.array(z.string()),
  risks: z.array(z.string()),
  raw_xml: z.string(),
  verify_commands: z.array(z.string()).optional(),
  // Strategy generated by the agent during the plan phase (PHASE-3-B).
  verify_strategy: z.string().optional(),
  // Structured verify assertions (spec 2026-05-08-verify-protocol-structured §3).
  // When non-empty, repair-loop uses these via runVerifyAssertions for native
  // structured diagnostics. verify_commands is preserved as a shell-only
  // fallback carrier for backward compat.
  verify_assertions: z.array(z.unknown()).optional(),
});

const verifyRoundSchema = z.object({
  round: z.number(),
  results: z.array(verifyResultSchema),
});

const staticScanFindingSchema = z.object({
  id: z.string(),
  scanner: z.string().default("generic"),
  file: z.string(),
  line: z.number().nullable(),
  column: z.number().nullable(),
  severity: z.enum(["critical", "high", "error", "medium", "warning", "low", "info"]),
  category: z.enum(["bug", "type", "style", "security", "secret", "dependency", "unknown"]).default("unknown"),
  message: z.string(),
  rule: z.string().nullable(),
  raw: z.unknown().optional(),
});

const staticScanRunSchema = z.object({
  round: z.number(),
  command: z.string(),
  status: z.enum(["passed", "failed"]),
  exit_code: z.number(),
  duration_ms: z.number(),
  output_path: z.string(),
  output_excerpt: z.string(),
  total_findings: z.number(),
  selected_top_n: z.array(staticScanFindingSchema),
  top_n_reasoning: z.array(z.string()),
  created_at: z.string(),
});

const staticRepairResultSchema = z.object({
  round: z.number(),
  scan_round: z.number(),
  selected_finding_ids: z.array(z.string()),
  strategy: z.string(),
  patch: z.string(),
  apply_status: z.enum(["ok", "failed", "skipped"]),
  files_changed: z.array(z.string()),
  post_scan_round: z.number().optional(),
  post_scan_status: z.enum(["passed", "failed", "skipped"]),
  remaining_findings: z.number(),
  error: z.string().optional(),
  created_at: z.string(),
});

const deepSeekUsageRecordSchema = z.object({
  phase: z.string(),
  model: z.string(),
  thinking: z.boolean(),
  duration_ms: z.number(),
  prompt: z.number(),
  completion: z.number(),
  total: z.number(),
  reasoning: z.number(),
  cache_hit: z.number(),
  cache_miss: z.number(),
  cache_hit_ratio: z.number(),
});

export const taskStateSchema = z.object({
  version: z.literal("0.1"),
  status: z.enum([
    "init",
    "planned",
    "preflighting",
    "preflighted",
    "preflight_failed",
    "patched",
    "verified",
    "verification_failed",
    "repairing",
    "repair_exhausted",
    "patch_failed",
    "patch_partial",
    "done",
  ]),
  task: z.object({
    description: z.string(),
    type: z.enum(["bugfix", "feature", "refactor", "test", "docs"]),
    created_at: z.string(),
    // Natural language goal for verification, provided by fixture or user (PHASE-3-B).
    verification_goal: z.string().optional(),
  }),
  plan: planSchema.optional(),
  patches: z.array(patchRecordSchema).default([]),
  patch_rounds: z.array(patchRoundSchema).default([]),
  tool_rounds: z.array(toolRoundRecordSchema).default([]),
  plan_contract_attempts: z.array(planContractAttemptSchema).default([]),
  preflight_results: z.array(verifyRoundSchema).default([]),
  verify_results: z.array(verifyRoundSchema).default([]),
  static_scan_runs: z.array(staticScanRunSchema).default([]),
  static_repair_results: z.array(staticRepairResultSchema).default([]),
  deepseek_usage: z.array(deepSeekUsageRecordSchema).default([]),
  repair_rounds: z.number().default(0),
  managed_files: z.array(z.string()).default([]),
  handoff_path: z.string().optional(),
});

export type TaskState = z.infer<typeof taskStateSchema>;
export type VerifyResult = z.infer<typeof verifyResultSchema>;
export type PatchRecord = z.infer<typeof patchRecordSchema>;
export type PatchRoundRecord = z.infer<typeof patchRoundSchema>;
export type ToolCallRecord = z.infer<typeof toolCallRecordSchema>;
export type ToolRoundRecord = z.infer<typeof toolRoundRecordSchema>;
export type PlanContractAttempt = z.infer<typeof planContractAttemptSchema>;
export type StaticScanFinding = z.infer<typeof staticScanFindingSchema>;
export type StaticScanRun = z.infer<typeof staticScanRunSchema>;
export type StaticRepairResult = z.infer<typeof staticRepairResultSchema>;
export type DeepSeekUsageRecord = z.infer<typeof deepSeekUsageRecordSchema>;

export type TaskStatus = TaskState["status"];

// ---- State machine ----

const VALID_TRANSITIONS: Record<TaskStatus, TaskStatus[]> = {
  "init": ["planned"],
  "planned": ["preflighting", "patched", "patch_failed", "patch_partial"],
  "preflighting": ["preflighted", "preflight_failed", "patch_failed", "patch_partial"],
  "preflighted": ["patched", "patch_failed", "patch_partial"],
  "preflight_failed": ["repairing", "repair_exhausted", "patched", "patch_failed", "patch_partial"],
  "patched": ["verified", "verification_failed"],
  "verified": ["done"],
  "verification_failed": ["repairing", "repair_exhausted"],
  "repairing": ["preflighting", "patched", "patch_failed", "patch_partial", "repair_exhausted"],
  "repair_exhausted": ["done"],
  "patch_failed": ["repairing", "repair_exhausted", "verification_failed"],
  // patch_partial: patch produced ≥1 change but required target coverage is
  // incomplete (spec §4.8). Routes straight to repair; never to "patched".
  "patch_partial": ["repairing", "repair_exhausted", "verification_failed"],
  "done": [],
};

export function canTransition(from: TaskStatus, to: TaskStatus): boolean {
  const allowed = VALID_TRANSITIONS[from];
  return allowed !== undefined && allowed.includes(to);
}

// ---- File I/O ----

export function readTaskState(cwd: string): TaskState | null {
  const dshRoot = findDshRoot(cwd);
  if (!dshRoot) return null;
  const filePath = path.join(dshRoot, "task-state.json");
  try {
    const raw = fs.readFileSync(filePath, "utf-8");
    const json = JSON.parse(raw);
    return taskStateSchema.parse(json);
  } catch {
    return null;
  }
}

export function writeTaskState(cwd: string, state: TaskState): void {
  const dshRoot = findDshRoot(cwd) ?? path.join(path.resolve(cwd), ".dsh");
  fs.mkdirSync(dshRoot, { recursive: true });
  const filePath = path.join(dshRoot, "task-state.json");
  fs.writeFileSync(filePath, JSON.stringify(state, null, 2), "utf-8");
  writeEvidenceFiles(dshRoot, state);
}

export function transition(
  state: TaskState,
  newStatus: TaskStatus,
): TaskState {
  if (!canTransition(state.status, newStatus)) {
    throw new Error(
      `Invalid state transition: ${state.status} -> ${newStatus}`,
    );
  }
  return { ...state, status: newStatus };
}

// ---- Factory ----

export function createTaskState(
  description: string,
  taskType: TaskState["task"]["type"],
  verificationGoal?: string,
): TaskState {
  return {
    version: "0.1",
    status: "init",
    task: {
      description,
      type: taskType,
      created_at: new Date().toISOString(),
      verification_goal: verificationGoal,
    },
    patches: [],
    patch_rounds: [],
    tool_rounds: [],
    plan_contract_attempts: [],
    preflight_results: [],
    verify_results: [],
    static_scan_runs: [],
    static_repair_results: [],
    deepseek_usage: [],
    repair_rounds: 0,
    managed_files: [],
  };
}

function writeEvidenceFiles(dshRoot: string, state: TaskState): void {
  fs.writeFileSync(path.join(dshRoot, "current-goal.md"), buildCurrentGoal(state), "utf-8");
  fs.writeFileSync(path.join(dshRoot, "plan.json"), JSON.stringify(state.plan ?? null, null, 2), "utf-8");
  fs.writeFileSync(path.join(dshRoot, "changed-files.json"), JSON.stringify(collectChangedFiles(state), null, 2), "utf-8");
  fs.writeFileSync(path.join(dshRoot, "tool-calls.jsonl"), collectToolCalls(state).map((r) => JSON.stringify(r)).join("\n"), "utf-8");
  fs.writeFileSync(path.join(dshRoot, "verify-result.json"), JSON.stringify(buildVerifyResult(state), null, 2), "utf-8");
  fs.writeFileSync(path.join(dshRoot, "plan-contract-diagnostics.json"), JSON.stringify(buildPlanContractDiagnostics(state), null, 2), "utf-8");
  fs.writeFileSync(path.join(dshRoot, "failure-evidence.md"), buildFailureEvidence(state), "utf-8");
  fs.writeFileSync(path.join(dshRoot, "repair-history.jsonl"), buildRepairHistory(state).map((r) => JSON.stringify(r)).join("\n"), "utf-8");
  fs.writeFileSync(path.join(dshRoot, "handoff.md"), buildStateHandoff(state), "utf-8");
}

function buildPlanContractDiagnostics(state: TaskState): Record<string, unknown> {
  const attempts = state.plan_contract_attempts ?? [];
  const lastInvalid = [...attempts].reverse().find((attempt) => attempt.status !== "valid");
  return {
    attempts,
    final_failure_reason: state.status === "planned" ? undefined : lastInvalid?.failure_reason,
    protocol_recovered: attempts.some((attempt) => attempt.protocol_recovered === true),
  };
}

function buildCurrentGoal(state: TaskState): string {
  const lines = [
    `# Current Goal`,
    "",
    `- Status: ${state.status}`,
    `- Type: ${state.task.type}`,
    `- Created: ${state.task.created_at}`,
    `- Task: ${state.task.description}`,
  ];
  if (state.task.verification_goal) {
    lines.push(`- Verification Goal: ${state.task.verification_goal}`);
  }
  return lines.join("\n") + "\n";
}

function collectChangedFiles(state: TaskState): string[] {
  const files = new Set<string>();
  for (const patch of state.patches) {
    for (const file of patch.files_changed) files.add(file);
  }
  for (const round of state.patch_rounds) {
    if (round.change?.apply_status === "ok") files.add(round.change.file);
  }
  return [...files].sort();
}

function collectToolCalls(state: TaskState): Array<Record<string, unknown>> {
  const records: Array<Record<string, unknown>> = [];
  for (const round of state.tool_rounds) {
    for (const call of round.calls) {
      records.push({ source: "tool_rounds", round: round.round, ...call });
    }
  }
  for (const round of state.patch_rounds) {
    for (const call of round.tool_calls ?? []) {
      records.push({ source: "patch_rounds", round: round.round, ...call });
    }
  }
  for (const patch of state.patches) {
    for (const toolRound of patch.tool_rounds ?? []) {
      for (const call of toolRound.calls) {
        records.push({ source: "patch_record", patchRound: patch.round, round: toolRound.round, ...call });
      }
    }
  }
  return records;
}

function buildVerifyResult(state: TaskState): Record<string, unknown> {
  const latest = state.verify_results.at(-1) ?? null;
  return {
    status: state.status,
    latest,
    all: state.verify_results,
  };
}

function buildFailureEvidence(state: TaskState): string {
  const lines = ["# Failure Evidence", ""];
  const failedVerifies = state.verify_results.flatMap((round) =>
    round.results
      .filter((result) => result.status === "failed")
      .map((result) => ({ round: round.round, result })),
  );
  const failedPatches = state.patches.filter((patch) => patch.apply_status === "failed" || patch.apply_status === "partial_ok");

  if (failedVerifies.length === 0 && failedPatches.length === 0 && state.status !== "repair_exhausted") {
    lines.push("No failure evidence recorded.");
    return lines.join("\n") + "\n";
  }

  for (const { round, result } of failedVerifies) {
    lines.push(`## Verify Round ${round}: ${result.command}`);
    lines.push("");
    lines.push(`- Exit code: ${result.exit_code}`);
    lines.push(`- Duration: ${result.duration_ms}ms`);
    lines.push("");
    lines.push("```");
    lines.push(result.output.slice(0, 8000));
    lines.push("```");
    lines.push("");
  }

  for (const patch of failedPatches) {
    lines.push(`## Patch Round ${patch.round}: ${patch.apply_status}`);
    lines.push("");
    if (patch.patch_incomplete_reason) lines.push(`- Incomplete: ${patch.patch_incomplete_reason}`);
    lines.push(`- Files changed: ${patch.files_changed.join(", ") || "(none)"}`);
    lines.push("");
  }

  return lines.join("\n") + "\n";
}

function buildRepairHistory(state: TaskState): Array<Record<string, unknown>> {
  return state.patches.map((patch) => {
    const verify = state.verify_results.find((round) => round.round === patch.round);
    return {
      round: patch.round,
      apply_status: patch.apply_status,
      files_changed: patch.files_changed,
      rolled_back: patch.rolled_back ?? false,
      rollback_reason: patch.rollback_reason,
      verify_status: verify
        ? verify.results.every((result) => result.status === "passed") ? "passed" : "failed"
        : "not-run",
      patch_incomplete_reason: patch.patch_incomplete_reason,
    };
  });
}

function buildStateHandoff(state: TaskState): string {
  const changedFiles = collectChangedFiles(state);
  const failed = state.verify_results.flatMap((round) => round.results.filter((result) => result.status === "failed"));
  const lines = [
    `# Handoff`,
    "",
    `## Completed`,
    "",
    changedFiles.length > 0 ? changedFiles.map((file) => `- Changed ${file}`).join("\n") : "- No changed files recorded.",
    "",
    `## Unfinished`,
    "",
    state.status === "verified" || state.status === "done"
      ? "- None recorded."
      : `- Current status is ${state.status}.`,
    "",
    `## Risks`,
    "",
    ...(state.plan?.risks?.length ? state.plan.risks.map((risk) => `- ${risk}`) : ["- No plan risks recorded."]),
    "",
    `## Evidence`,
    "",
    `- Verify rounds: ${state.verify_results.length}`,
    `- Failed verify commands: ${failed.length}`,
    `- Repair rounds: ${state.repair_rounds}`,
    "",
    `## Next Steps`,
    "",
    state.status === "verified" || state.status === "done"
      ? "- Review final diff and commit."
      : "- Inspect failure-evidence.md and repair-history.jsonl before continuing.",
  ];
  return lines.join("\n") + "\n";
}
